# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chiril Ungureanu
title: Web Developer | Triple Certified Drupal Expert - Drupal 10
email: ungureanu.chiril@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  chiril-ungureanu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: chiril-ungureanu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Chiril and I'm a web developer with 5 years of experience building and maintaining custom Drupal-based websites. 
  
  Proficient in Drupal 8, 9 and 10. Strong problem-solving and analytical skills, combined with a passion for technology and innovation, make me an asset to any organization looking to implement cutting-edge Drupal solutions.

content:

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <div class="container mt-5">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <h4>Hard Skills:</h4>
            <ul>
              <li>Drupal 8-10</li>
              <li>RESTful APIs / GraphQL / JSON:API</li>
              <li>Data Migration</li>
              <li>PHP 7-8</li>
              <li>JavaScript / jQuery / AJAX / React</li>
              <li>Twig</li>
              <li>MySQL / MongoDB</li>
              <li>Git</li>
              <li>Docker</li>
              <li>CI/CD</li>
              <li>Composer and Dependency Management</li>
              <li>OOP</li>
              <li>Drupal Commerce for E-commerce Solutions</li>
              <li>Multisite Setup and Management</li>
            </ul>
          </div>
          <div class="col-md-6">
            <h4>Soft Skills:</h4>
            <ul>
              <li>Communication and Collaboration</li>
              <li>Problem-Solving and Troubleshooting</li>
              <li>Adaptability and Flexibility</li>
              <li>Time Management and Organization</li>
              <li>Attention to Detail and Accuracy</li>
              <li>Teamwork and Interpersonal Skills</li>
            </ul>
          </div>
        </div>
      </div>


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IT Step Academy
        caption: 2017 - 2019
        sub_title: Software Developer
        description: | # this will include new lines to allow paragraphs
          **Relevant coursework**: 
            - Computer Basics: Understanding Operating Systems
            - Introduction to Data Structures and Algorithms
            - Object-Oriented Programming In C++
            - Database Concepts
            - Microsoft SQL Server
            - Oracle Database
            - Basics of Computer Networking
            - JavaScript
            - HTML / CSS
            - C# / MVC
            - UML

  - title: Certification # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Acquia Certification Program
        description: | # this will include new lines to allow paragraphs
          - Triple Certified Drupal Expert - Drupal 10 - 2023
      - layout: left
        title: Acquia Certification Program
        description: | # this will include new lines to allow paragraphs
          - Acquia Certified Back End Specialist - Drupal 10 - 2023
      - layout: left
        title: Acquia Certification Program
        description: | # this will include new lines to allow paragraphs
          - Acquia Certified Developer - Drupal 10 - 2023
      - layout: left
        title: Acquia Certification Program
        description: | # this will include new lines to allow paragraphs
          - Acquia Certified Front End Specialist - Drupal 10 - 2023
      - layout: left
        title: Acquia Certification Program
        description: | # this will include new lines to allow paragraphs
          - Acquia Certified Developer - 2021

  - title: Languages # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **English:** Intermediate
      - **Romanian:** Native
      - **Russian:** Advanced

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FFW Agency
        sub_title: Drupal Developer
        caption: May 2021 - Present
        description: |
          #### Responsibility:
          - Designing and developing custom Drupal modules to extend the functionality of the Drupal platform and meet specific project requirements.
          - Integrating third-party APIs and services with Drupal to enable seamless data exchange and interaction with external systems.
          - Customizing and configuring Drupal core and contributed modules to match project needs and requirements.
          - Identifying and resolving backend issues, bugs, and errors through thorough debugging and testing.
          - Implementing and managing data structures, content types, and fields in Drupal to organize and store website content efficiently.
          
          ### Projects
          ## Superbook
          CBN's Superbook Kids website is a safe place for your kids to play free online games, learn more about the Bible, and grow in their faith!
          #### Responsibility:
          - Designing and implementing GraphQL endpoints in Drupal to enable efficient querying and retrieval of data from custom entities and other Drupal content.
          - Creating custom entities in Drupal to store and manage project-specific data in a structured manner.
          - Createing views listing pages in Drupal to display and organize content in a user-friendly way.
          - Developing a WYSIWYG plugin and custom filters to automatically convert Bible references into Bible verses.
          - Implementing seamless integration between Drupal Paragraphs and Storybook components.

          **Technologies used:** Drupal 9, PHP 8, GraphQL 4, Twig, Storybook, React, Git, Docker 


          ## Baker Institute
          The Baker Institute for Public Policy is a nonpartisan, data-driven think tank located on the campus of Rice University.
          #### Responsibility:
          - Migration of the content from the old website with NoSQL database to Drupal 9 with SQL database.
          - Creating custom tokens in Drupal to generate dynamic content for Site Studio.
          - Createing views listing pages in Drupal to display and organize content in a user-friendly way.
          - Developing custom Views filters that enable users to filter by both nodes and terms simultaneously.
          - Configuring CI/CD pipelines in CircleCI to automate the deployment process.

          **Technologies used:** Drupal 9, PHP 8, Site Studio, JavaScript, Twig, Git, Docker


          ## NBC Sports Regional Networks
          NBC Sports Regional Networks is the collective name for a group of regional sports networks in the United States.
          #### Responsibility:
          - Improve Apple News by adding more features and capabilities to enhance its functionality.
          - Developing an integration with OneTrust to ensure compliance with GDPR and CCPA regulations.
          - Developing an integration with Chartbeat to enable real-time analytics and reporting.
          - Enhancing and optimizing the website's Accelerated Mobile Pages (AMP) version for improved user experience.
          - Identify and fix bugs in the codebase to ensure smooth functionality and optimal performance.
          - Core and contributed module updates.

          **Technologies used:** Drupal 9, PHP 8, AMP, JavaScript, Twig, Git, Docker


      - layout: left
        title: Indrivo
        sub_title: Drupal Developer
        caption: May 2019 - May 2021
        description: |
          #### Responsibility:
          - Developing custom Drupal modules to extend Drupal Commerce functionality and meet specific project requirements.
          - Integrating third-party APIs and services with Drupal to enable seamless data exchange and interaction with external systems.
          - Customizing and configuring Drupal core and contributed modules to match project needs and requirements.
          - Identifying and resolving backend issues, bugs, and errors through thorough debugging and testing.
          - Implementing and managing data structures, content types, and fields in Drupal to organize and store website content efficiently.
          
          ### Projects

          ## SELIA.md marketplace
          Selia is becoming one of the fastest-growing marketplaces in Moldova.
          #### Responsibility:
          - Developing bespoke Drupal modules to facilitate data synchronization between the marketplace and sellers.
          - Developing a REST API to synchronize the marketplace with external sellers.

          **Technologies used:** Drupal 8-9, PHP 7, REST API


          ## SMS authentication
          Integrating SMS authentication into an intranet platform, enabling users to authenticate themselves using a one-time passcode delivered via SMS
          #### Responsibility:
          - MDeveloping integration with the Twilio SMS gateway to enable SMS authentication.

          **Technologies used:** Drupal 8-9, PHP 7, Twilio API


          ## Goadventure
          GoAdventure provides different tours for tourist visiting Moldova. Winery tours, city tours, monastery tours and also trips to Transnistria and Tiraspol.
          #### Responsibility:
          - Implementing the booking functionalityand itinerary guide.
          - Developing a custom flow for reservations and reservations management.

          **Technologies used:** Drupal 8, PHP 7, Drupal Commerce, JavaScript, Twig


          ## Victoriabank payment system
          The goal of the project is to develop a Drupal commerce payment module for Victoriabank.
          #### Responsibility:
          - Creating a custom payment module for Drupal Commerce.

          **Technologies used:** Drupal 8, PHP 7, Drupal Commerce, Victoriabank API


          ## Moldova-Agroinbank payment system
          The goal of the project is to develop a Drupal commerce payment module for Moldova-Agroinbank.
          #### Responsibility:
          - Creating a custom payment module for Drupal Commerce.

          **Technologies used:** Drupal 8, PHP 7, Drupal Commerce, Moldova-Agroinbank API


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
